import { ObservedMapMap } from "../interfaces/ObservedMapMap";
import { AnyIdListenerCallback, IdListenerCallback } from "../Listeners";
export declare class ObservedMapMapMirror<CONTENT, SUB_CONTENT> implements ObservedMapMap<CONTENT, SUB_CONTENT> {
    private map;
    private observedKeys;
    size: number;
    constructor(map: ObservedMapMap<CONTENT, SUB_CONTENT>);
    [Symbol.iterator](): IterableIterator<[string, CONTENT]>;
    entries(): IterableIterator<[string, CONTENT]>;
    [Symbol.toStringTag]: string;
    addAnySubIdListener(id: string, listener: AnyIdListenerCallback): void;
    addSubIdListener(id: string, subId: string, listener: IdListenerCallback): void;
    hasSub(id: string, subId: string): boolean;
    getMap(id: string): Map<string, SUB_CONTENT> | undefined;
    getSub(id: string, subId: string): SUB_CONTENT | undefined;
    forEachSub(id: string, callback: (value: SUB_CONTENT, key: string) => void): void;
    awaitForEachSub(id: string, callback: (value: SUB_CONTENT, key: string) => Promise<void>): void;
    keysSub(id: string): IterableIterator<string>;
    valuesSub(id: string): IterableIterator<SUB_CONTENT>;
    sizeSub(id: string): number;
    setSub(id: string, subId: string, data: SUB_CONTENT): void;
    deleteSub(id: string, subId: string): void;
    modifySub(id: string, subId: string, data?: Object): void;
    clearSub(id: string): void;
    addAnyIdListener(listener: AnyIdListenerCallback): void;
    addIdListener(id: string, listener: IdListenerCallback): void;
    get(id: string): CONTENT | undefined;
    set(id: string, data: CONTENT): this;
    has(id: string): boolean;
    delete(id: string): boolean;
    modify(id: string, data?: Object): void;
    clear(): void;
    keys(): IterableIterator<string>;
    values(): IterableIterator<CONTENT>;
    forEach(callback: (value: CONTENT, key: string, map: Map<string, CONTENT>) => void): void;
    awaitForEach(callback: (value: CONTENT, key: string) => Promise<void>): void;
    addObservedKey(key: string): void;
    deleteObservedKey(key: string): void;
}
